---
self-hosted-runner:
  labels: [code-review]

config-variables: null

paths:
  .github/workflows/**/*.yml:
    ignore:
      - "SC2016:.+"
  .github/workflows/enforce-repo-settings.yml:
    ignore:
      - 'property "repo_settings_token" is not defined'
