rules:
  pull-request-target:
    level: ignore
  unpinned-uses:
    level: warn
  artipacked:
    level: ignore
  dangerous-triggers:
    level: ignore
  bot-conditions:
    level: ignore
  dependabot-cooldown:
    level: ignore
  template-injection:
    level: ignore
