#!/usr/bin/env bash
# Security contracts for managed pull-request workflows.
set -euo pipefail

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
FAIL=0
pass() { printf '[OK] %s\n' "$1"; }
fail() {
  printf '[FAIL] %s\n' "$1" >&2
  FAIL=1
}
require_literal() {
  if grep -Fq -- "$2" "$1"; then pass "$3"; else fail "$3"; fi
}
reject_literal() {
  if grep -Fq -- "$2" "$1"; then fail "$3"; else pass "$3"; fi
}

managed="$REPO_ROOT/workflows/require-linked-issue.yml"
central="$REPO_ROOT/.github/workflows/require-linked-issue.yml"
super_linter="$REPO_ROOT/workflows/super-linter.yml"
require_literal "$super_linter" '  linked-issue:' "managed Super-Linter preserves the canonical linked-issue job ID"
reject_literal "$super_linter" '  xcsh-linked-issue:' "managed Super-Linter excludes the incompatible xcsh-prefixed job ID"

for file in "$managed" "$central"; do
  require_literal "$file" '  pull_request:' "${file#"$REPO_ROOT/"} triggers on pull requests"
  require_literal "$file" '    types: [opened, reopened, edited, synchronize]' "${file#"$REPO_ROOT/"} covers link transitions"
  require_literal "$file" 'permissions: {}' "${file#"$REPO_ROOT/"} denies default workflow token permissions"
  require_literal "$file" 'github.event.pull_request.head.repo.full_name == github.repository' "${file#"$REPO_ROOT/"} skips fork pull requests"
  require_literal "$file" 'Check linked issues' "${file#"$REPO_ROOT/"} emits the exact check context"
  require_literal "$file" '      pull-requests: read' "${file#"$REPO_ROOT/"} grants pull-request read access"
  require_literal "$file" 'closingIssuesReferences(first: 1)' "${file#"$REPO_ROOT/"} queries only one closing issue"
  require_literal "$file" "Add 'Closes #123'" "${file#"$REPO_ROOT/"} provides actionable guidance"
  for forbidden in schedule pull_request_target actions/checkout github.paginate createCommitStatus createComment EXCLUDE_BRANCHES 'issues: write' 'statuses: write'; do
    reject_literal "$file" "$forbidden" "${file#"$REPO_ROOT/"} excludes retired $forbidden surface"
  done
done
require_literal "$central" '    runs-on: managed-socketless' 'central linked-issue workflow routes to managed ARC'
require_literal "$managed" "github.repository == 'f5-sales-demo/docs-icons' && 'docs-socketless' || 'managed-socketless'" \
  'managed linked-issue caller selects the docs-icons ARC scale set'

reject_literal "$managed" workflow_dispatch 'managed caller excludes central-only workflow dispatch'
require_literal "$managed" "!startsWith(github.event.pull_request.head.ref, 'governance/reconcile-')" \
  'managed caller skips centrally attested reconciliation PRs'
require_literal "$managed" '  group: require-linked-issue-${{ github.event.pull_request.number }}' \
  'managed caller serializes checks per pull request'
require_literal "$managed" '  cancel-in-progress: true' \
  'managed caller cancels superseded checks'

for file in "$managed" "$super_linter"; do
  require_literal "$file" 'RELEASE_AUTOMATION_LOGIN:' \
    "${file#"$REPO_ROOT/"} receives the configured release identity"
  require_literal "$file" 'pull.user?.login === process.env.RELEASE_AUTOMATION_LOGIN' \
    "${file#"$REPO_ROOT/"} authenticates the configured release PR author"
  require_literal "$file" 'pull.head?.repo?.full_name' \
    "${file#"$REPO_ROOT/"} requires the current repository"
  require_literal "$file" '^release\/v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$' \
    "${file#"$REPO_ROOT/"} requires a canonical release branch"
  require_literal "$file" '^chore: bump version to v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$' \
    "${file#"$REPO_ROOT/"} requires a matching canonical release title"
  require_literal "$file" 'pull.body?.startsWith("Automated release PR generated by ")' \
    "${file#"$REPO_ROOT/"} requires the generator body marker"
done
for file in "$managed" "$central" "$super_linter"; do
  require_literal "$file" 'RENOVATE_GITHUB_APP_BOT_ID:' \
    "${file#"$REPO_ROOT/"} receives the numeric Renovate identity"
  require_literal "$file" 'pull.user?.type === "Bot"' \
    "${file#"$REPO_ROOT/"} requires a GitHub Bot actor"
  require_literal "$file" 'pull.user?.id === renovateId' \
    "${file#"$REPO_ROOT/"} authenticates the exact numeric Renovate actor"
done
require_literal "$super_linter" "github.repository == 'f5-sales-demo/xcsh' && 'xcsh-socketless' || 'managed-socketless'" \
  'managed Super-Linter preserves repository-scoped xcsh routing'
require_literal "$super_linter" "github.repository == 'f5-sales-demo/xcsh' && '2024' || '2021'" \
  'managed Super-Linter preserves the xcsh Rust edition'
for config in "$REPO_ROOT/.github/config/repo-settings.json" "$REPO_ROOT/.claude/governance.json"; do
  if jq -e '.managed_files?.skip_files.xcsh // .skip_files.xcsh | index(".github/workflows/super-linter.yml") == null' \
    "$config" >/dev/null; then
    pass "${config#"$REPO_ROOT/"} centrally manages the xcsh Super-Linter caller"
  else
    fail "${config#"$REPO_ROOT/"} must not exempt the xcsh Super-Linter caller"
  fi
done

reject_literal "$central" '  workflow_dispatch:' 'PR workflow cannot publish dispatched manifest receipts'
require_literal "$central" "'Validate manifest receipt candidate' || 'Check linked issues'" \
  'central PR workflow selects a non-required manifest candidate context'
require_literal "$central" "startsWith(github.event.pull_request.head.ref, 'sync/manifest-')" \
  'central PR workflow isolates immutable manifest branches'
require_literal "$central" 'Manifest candidate is not one exact manifest-only commit' \
  'central PR workflow validates candidate ancestry and diff shape'
require_literal "$central" '      contents: read' \
  'central PR workflow can inspect manifest candidate ancestry'
require_literal "$central" '  group: require-linked-issue-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}' \
  'central PR workflow serializes each exact pull request head'
require_literal "$central" '  cancel-in-progress: true' \
  'central PR workflow cancels only superseded matching checks'
attestor="$REPO_ROOT/.github/workflows/attest-manifest-linked-issue.yml"
require_literal "$attestor" '  workflow_dispatch:' 'protected-main attestor exposes explicit dispatch'
require_literal "$attestor" 'expected_source_sha:' 'attestor requires an exact source SHA'
require_literal "$attestor" 'expected_head_sha:' 'attestor requires an exact head SHA'
require_literal "$attestor" '      checks: write' 'attestor alone can publish the required receipt'
require_literal "$attestor" 'filter: "all"' 'attestor inventories all duplicate receipts'
require_literal "$attestor" 'external_id: externalId' 'attestor binds a deterministic external receipt'
reject_literal "$attestor" 'actions/checkout' 'attestor does not execute pull request content'
if jq -e '[.hosted_exceptions | to_entries[] |
  select(.value[".github/workflows/require-linked-issue.yml"] != null)] | length == 0' \
  "$REPO_ROOT/.github/config/self-hosted-runner-policy.json" >/dev/null; then
  pass 'fleet runner policy excludes every retired linked-issue hosted exception'
else
  fail 'fleet runner policy excludes every retired linked-issue hosted exception'
fi
pass 'central and downstream linked-issue workflows have intentionally separate contracts'

for file in "$REPO_ROOT/workflows/auto-merge.yml" "$REPO_ROOT/.github/workflows/auto-merge.yml"; do
  require_literal "$file" "github.event.pull_request.user.type == 'User'" \
    "${file#"$REPO_ROOT/"} limits generic auto-merge to humans"
  require_literal "$file" "format('{0}', github.event.pull_request.user.id) != vars.RENOVATE_GITHUB_APP_BOT_ID" \
    "${file#"$REPO_ROOT/"} explicitly excludes the numeric Renovate identity"
done
require_literal "$REPO_ROOT/workflows/auto-merge.yml" "github.repository == 'f5-sales-demo/docs-icons' && 'docs-socketless' || 'managed-socketless'" \
  'managed auto-merge caller selects the docs-icons ARC scale set'
for retired in "$REPO_ROOT/.github/dependabot.yml" "$REPO_ROOT/.github/workflows/dependabot-auto-merge.yml" "$REPO_ROOT/workflows/dependabot-auto-merge.yml"; do
  if [ -e "$retired" ]; then fail "${retired#"$REPO_ROOT/"} is retired"; else pass "${retired#"$REPO_ROOT/"} is absent"; fi
done

if node "$REPO_ROOT/tests/privileged-pr-workflow-behavior.mjs" "$REPO_ROOT"; then
  pass 'linked-issue workflow behavior matches its exact-PR API contract'
else
  fail 'linked-issue workflow behavior must match its exact-PR API contract'
fi

if [ "$FAIL" -eq 0 ]; then
  printf 'PASS: linked-issue workflow contract is secure\n'
else
  printf 'FAIL: linked-issue workflow contract is incomplete\n' >&2
fi
exit "$FAIL"
