#!/usr/bin/env bash
# Security contracts for managed pull-request workflows.
set -euo pipefail

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
FAIL=0
pass() { printf '[OK] %s\n' "$1"; }
fail() {
  printf '[FAIL] %s\n' "$1" >&2
  FAIL=1
}
require_literal() {
  if grep -Fq -- "$2" "$1"; then pass "$3"; else fail "$3"; fi
}
reject_literal() {
  if grep -Fq -- "$2" "$1"; then fail "$3"; else pass "$3"; fi
}

managed="$REPO_ROOT/workflows/require-linked-issue.yml"
central="$REPO_ROOT/.github/workflows/require-linked-issue.yml"
super_linter="$REPO_ROOT/workflows/super-linter.yml"
require_literal "$super_linter" '  linked-issue:' "managed Super-Linter preserves the canonical linked-issue job ID"
reject_literal "$super_linter" '  xcsh-linked-issue:' "managed Super-Linter excludes the incompatible xcsh-prefixed job ID"

for file in "$managed" "$central"; do
  require_literal "$file" '  pull_request:' "${file#"$REPO_ROOT/"} triggers on pull requests"
  require_literal "$file" '    types: [opened, reopened, edited, synchronize]' "${file#"$REPO_ROOT/"} covers link transitions"
  require_literal "$file" 'permissions: {}' "${file#"$REPO_ROOT/"} denies default workflow token permissions"
  require_literal "$file" 'github.event.pull_request.head.repo.full_name == github.repository' "${file#"$REPO_ROOT/"} skips fork pull requests"
  require_literal "$file" '    name: Check linked issues' "${file#"$REPO_ROOT/"} emits the exact check context"
  require_literal "$file" '    runs-on: managed-socketless' "${file#"$REPO_ROOT/"} routes to repository-scoped ARC"
  require_literal "$file" '      pull-requests: read' "${file#"$REPO_ROOT/"} grants pull-request read access"
  require_literal "$file" 'closingIssuesReferences(first: 1)' "${file#"$REPO_ROOT/"} queries only one closing issue"
  require_literal "$file" "Add 'Closes #123'" "${file#"$REPO_ROOT/"} provides actionable guidance"
  for forbidden in schedule pull_request_target actions/checkout github.paginate createCommitStatus createComment EXCLUDE_BRANCHES 'issues: write' 'statuses: write'; do
    reject_literal "$file" "$forbidden" "${file#"$REPO_ROOT/"} excludes retired $forbidden surface"
  done
done

reject_literal "$managed" workflow_dispatch 'managed caller excludes central-only workflow dispatch'
require_literal "$managed" "!startsWith(github.event.pull_request.head.ref, 'governance/reconcile-')" \
  'managed caller skips centrally attested reconciliation PRs'
require_literal "$managed" '  group: require-linked-issue-${{ github.event.pull_request.number }}' \
  'managed caller serializes checks per pull request'
require_literal "$managed" '  cancel-in-progress: true' \
  'managed caller cancels superseded checks'

for file in "$managed" "$super_linter"; do
  require_literal "$file" 'RELEASE_AUTOMATION_LOGIN:' \
    "${file#"$REPO_ROOT/"} receives the configured release identity"
  require_literal "$file" 'pull.user?.login === process.env.RELEASE_AUTOMATION_LOGIN' \
    "${file#"$REPO_ROOT/"} authenticates the configured release PR author"
  require_literal "$file" 'pull.head?.repo?.full_name' \
    "${file#"$REPO_ROOT/"} requires the current repository"
  require_literal "$file" '^release\/v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$' \
    "${file#"$REPO_ROOT/"} requires a canonical release branch"
  require_literal "$file" '^chore: bump version to v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$' \
    "${file#"$REPO_ROOT/"} requires a matching canonical release title"
  require_literal "$file" 'pull.body?.startsWith("Automated release PR generated by ")' \
    "${file#"$REPO_ROOT/"} requires the generator body marker"
done
require_literal "$super_linter" "github.repository == 'f5-sales-demo/xcsh' && 'xcsh-socketless' || 'managed-socketless'" \
  'managed Super-Linter preserves repository-scoped xcsh routing'
require_literal "$super_linter" "github.repository == 'f5-sales-demo/xcsh' && '2024' || '2021'" \
  'managed Super-Linter preserves the xcsh Rust edition'
for config in "$REPO_ROOT/.github/config/repo-settings.json" "$REPO_ROOT/.claude/governance.json"; do
  if jq -e '.managed_files?.skip_files.xcsh // .skip_files.xcsh | index(".github/workflows/super-linter.yml") == null' \
    "$config" >/dev/null; then
    pass "${config#"$REPO_ROOT/"} centrally manages the xcsh Super-Linter caller"
  else
    fail "${config#"$REPO_ROOT/"} must not exempt the xcsh Super-Linter caller"
  fi
done

require_literal "$central" '  workflow_dispatch:' 'central implementation exposes exact-receipt dispatch'
require_literal "$central" 'pull_request_number:' 'central dispatch requires a PR number'
require_literal "$central" 'expected_head_sha:' 'central dispatch requires an exact head SHA'
require_literal "$central" 'pull.data.head.sha !== process.env.EXPECTED_HEAD_SHA' \
  'central dispatch verifies the current PR head'
require_literal "$central" 'pull.data.head.repo?.full_name !== `${owner}/${repo}`' \
  'central dispatch verifies same-repository ownership'
require_literal "$central" '      contents: read' 'central dispatch receives only the extra content read scope it needs'
require_literal "$central" "  group: require-linked-issue-\${{ github.event_name }}-\${{ github.event.pull_request.number || inputs.pull_request_number }}-\${{ inputs.expected_head_sha || 'live' }}" \
  'central implementation separates live PR and exact-receipt concurrency identities'
require_literal "$central" '  cancel-in-progress: true' \
  'central implementation cancels only superseded matching checks'
if jq -e '[.hosted_exceptions | to_entries[] |
  select(.value[".github/workflows/require-linked-issue.yml"] != null)] | length == 0' \
  "$REPO_ROOT/.github/config/self-hosted-runner-policy.json" >/dev/null; then
  pass 'fleet runner policy excludes every retired linked-issue hosted exception'
else
  fail 'fleet runner policy excludes every retired linked-issue hosted exception'
fi
pass 'central and downstream linked-issue workflows have intentionally separate contracts'

if node "$REPO_ROOT/tests/privileged-pr-workflow-behavior.mjs" "$REPO_ROOT"; then
  pass 'linked-issue workflow behavior matches its exact-PR API contract'
else
  fail 'linked-issue workflow behavior must match its exact-PR API contract'
fi

if [ "$FAIL" -eq 0 ]; then
  printf 'PASS: linked-issue workflow contract is secure\n'
else
  printf 'FAIL: linked-issue workflow contract is incomplete\n' >&2
fi
exit "$FAIL"
